spring.application.name=employee-management

spring.datasource.url=jdbc:mysql://${DB_HOST:mysql-db}:3306/employeedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:employee}
spring.datasource.password=${DB_PASSWORD:employee123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=8080
